global:
  scrape_interval: 15s     
  evaluation_interval: 15s  

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth"
    static_configs:
      - targets: ["auth:8001"]   
    metrics_path: "/metrics"

  - job_name: "inventory"
    static_configs:
      - targets: ["inventory:8002"]
    metrics_path: "/metrics"

  - job_name: "trade"
    static_configs:
      - targets: ["trade:8003"]
    metrics_path: "/metrics"